apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
  namespace: jenkins
type: Opaque
data:
  azurestorageaccountname: Y2ljZHByb2plY3RzdG9yYWdl
  azurestorageaccountkey: WWR6bjlwZVJLZ2NYYjdGbTFybjU0dUVmUzVldHBjS0Zvekd3ZldMc05OcFByWWJvTTd0RzRPNGJoMFYvTVlSaEU3a2tBSHFuNUlXbytBU3RSTU12MXc9PQ==
