apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: <your-resource-group>
spec:
  type: LoadBalancer
  loadBalancerIP: <your-public-ip>
  selector:
    app: istio-ingressgateway
  ports:
    - name: http2
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: tcp
      protocol: TCP
      port: 31400
      targetPort: 31400
    - name: tls
      protocol: TCP
      port: 15443
      targetPort: 15443
