apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
  namespace: jenkins-slave
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICAgICAiYXV0aHMiOgogICAgICAgIHsKICAgICAgICAgICJhemRldm9wc2NvdXJzZS5henVyZWNyLmlvIjoKICAgICAgICAgICAgewogICAgICAgICAgICAgICJ1c2VybmFtZSI6ICJhemRldm9wc2NvdXJzZSIsCiAgICAgICAgICAgICAgInBhc3N3b3JkIjogIlFYYnNwNnNaenVkR2k5M0s1UGVta1VrYmdZMUlKVXNRVng2MVlMNEpPVitBQ1JDRGF4b3UiLAogICAgICAgICAgICAgICJlbWFpbCI6ICJpc3VydXBhdGh1bWhlcmF0aEBnbWFpbC5jb20iLAogICAgICAgICAgICAgICJhdXRoIjogIllYcGtaWFp2Y0hOamIzVnljMlU2VVZoaWMzQTJjMXA2ZFdSSGFUa3pTelZRWlcxclZXdGlaMWt4U1VwVmMxRldlRFl4V1V3MFNrOVdLMEZEVWtORVlYaHZkUT09IiwKICAgICAgICAgICAgfSwKICAgICAgICB9LAogICAgfQ==
